name: demo workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SERVER_HOST: 5.63.152.168
  SERVER_USER: root
  SERVER_PATH: /var/www/test_front

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          php-version: '7.2.5'
      - name: Copy env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      # Install ssh key
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: "${{ secrets.MY_KEY }}"
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"
      - name: Generate auth hosts
        run: ssh-keyscan -H ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts
      # Deploy
      - run: rsync --archive --compress --progress . ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.SERVER_PATH }}